export const KEY = 'carz';

export const CAR_ATTRIBUTES = [
  'Accessory Power Outlet',
  'Additional Features Comfort',
  'Additional Features Entertainment',
  'Additional Features Exterior',
  'Additional Features Interior',
  'Advance Safety Features',
  'Air Conditioner',
  'Alloy Wheel Size',
  'Alloy Wheels',
  'Android Auto',
  'Anti Lock Braking System',
  'Anti-Lock Braking System',
  'Apple CarPlay',
  'Bluetooth Connectivity',
  'Body Type',
  'Brake Assist',
  'Brand',
  'Central Locking',
  'Connectivity',
  'Cruise Control',
  'Displacement (cc)',
  'Driver Airbag',
  'Driving Experience Control Eco',
  'EBD',
  'Electric Folding Rear View Mirror',
  'Engine Displacement (cc)',
  'Fabric Upholstery',
  'Foldable Rear Seat',
  'Fuel Type',
  'Gear Box',
  'Heater',
  'Height Adjustable Driver Seat',
  'Hill Assist',
  'History',
  'Insurance',
  'Integrated 2DIN Audio',
  'Kilometer Driven',
  'Knee Airbags',
  'Last Service',
  'Max Power (bhp@rpm)',
  'Max Power',
  'Max Torque',
  'Mild Hybrid',
  'Model',
  'Multi-function Steering Wheel',
  'No of Airbags',
  'No. of cylinder',
  'Outside Rear View Mirror Turn Indicators',
  'Outside Temperature Display',
  'Owner',
  'Passenger Airbag',
  'Pics',
  'Power Adjustable Exterior Rear View Mirror',
  'Power Door Locks',
  'Radio',
  'Rear AC Vents',
  'Registered In',
  'Registration',
  'Seating Capacity',
  'Speakers Front',
  'Speakers Rear',
  'Sr. No.',
  'Steering Column',
  'Steering Type',
  'Touch Screen size',
  'Touch Screen',
  'TransmissionType',
  'Tyre Size',
  'USB & Auxiliary input',
  'Valves Per Cylinder',
  'Vehicle Stability Control System',
];
